name: Fortran Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system level dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          sudo apt-get install libopenblas-dev

      - name: Install GauOpen
        run: |
          mkdir gauopen
          cd gauopen
          wget http://gaussian.com/g16/gauopen_v2.zip
          unzip gauopen_v2.zip
          cd ..

      - name: Build mqcPack
        run: |
          mkdir mqc-install
          echo -e "yG$GITHUB_WORKSPACE/mqc-install\n-lblas\n-llapack\n$GITHUB_WORKSPACE/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile

